---
title: "Load Testing"
output: html_document
date: "2025-12-01"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(ggthemes)
```


# Data loading

```{r}
base_path <- "../data/clean/"
normal_1rpsX2min <- read_csv(paste0(base_path, "load-test_1rps-2min_normal.jtl"))
normal_3rpsX2min <- read_csv(paste0(base_path, "load-test_3rps-2min_normal.jtl"))
normal_5rpsX2min <- read_csv(paste0(base_path, "load-test_5rps-2min_normal.jtl"))
normal_7rpsX2min <- read_csv(paste0(base_path, "load-test_7rps-2min_normal.jtl"))
normal_10rpsX2min <- read.csv(paste0(base_path, "load-test_10rps-2min_normal.jtl"))
cache_1rpsX2min <- read_csv(paste0(base_path, "load-test_1rps-2min_cache.jtl"))
cache_3rpsX2min <- read_csv(paste0(base_path, "load-test_3rps-2min_cache.jtl"))
cache_5rpsX2min <- read_csv(paste0(base_path, "load-test_5rps-2min_cache.jtl"))
cache_7rpsX2min <- read_csv(paste0(base_path, "load-test_7rps-2min_cache.jtl"))
cache_10rpsX2min <- read_csv(paste0(base_path, "load-test_10rps-2min_cache.jtl"))

normal_1rpsX2min$responseCode <- as.character(normal_1rpsX2min$responseCode)
normal_3rpsX2min$responseCode <- as.character(normal_3rpsX2min$responseCode)
normal_5rpsX2min$responseCode <- as.character(normal_5rpsX2min$responseCode)
normal_7rpsX2min$responseCode <- as.character(normal_7rpsX2min$responseCode)
normal_10rpsX2min$responseCode <- as.character(normal_10rpsX2min$responseCode)
cache_1rpsX2min$responseCode <- as.character(cache_1rpsX2min$responseCode)
cache_3rpsX2min$responseCode <- as.character(cache_3rpsX2min$responseCode)
cache_5rpsX2min$responseCode <- as.character(cache_5rpsX2min$responseCode)
cache_7rpsX2min$responseCode <- as.character(cache_7rpsX2min$responseCode)
cache_10rpsX2min$responseCode <- as.character(cache_10rpsX2min$responseCode)
```

# Normalize the timestamp

```{r}
normalize <- function(timestamp_col) {
  minimum <- min(timestamp_col)
  maximum <- max(timestamp_col)
  timestamp_norm <- (timestamp_col - minimum) / (maximum - minimum)
  return(timestamp_norm)
}
```

Execute in each dataset.
```{r}
normal_1rpsX2min$timeStamp <- normalize(normal_1rpsX2min$timeStamp)
normal_3rpsX2min$timeStamp <- normalize(normal_3rpsX2min$timeStamp)
normal_5rpsX2min$timeStamp <- normalize(normal_5rpsX2min$timeStamp)
normal_7rpsX2min$timeStamp <- normalize(normal_7rpsX2min$timeStamp)
normal_10rpsX2min$timeStamp <- normalize(normal_10rpsX2min$timeStamp)
cache_1rpsX2min$timeStamp <- normalize(cache_1rpsX2min$timeStamp)
cache_3rpsX2min$timeStamp <- normalize(cache_3rpsX2min$timeStamp)
cache_5rpsX2min$timeStamp <- normalize(cache_5rpsX2min$timeStamp)
cache_7rpsX2min$timeStamp <- normalize(cache_7rpsX2min$timeStamp)
cache_10rpsX2min$timeStamp <- normalize(cache_10rpsX2min$timeStamp)
```

# Joining data sources

```{r}
normal_1rpsX2min$mode <- "normal"
normal_3rpsX2min$mode <- "normal"
normal_5rpsX2min$mode <- "normal"
normal_7rpsX2min$mode <- "normal"
normal_10rpsX2min$mode <- "normal"
cache_1rpsX2min$mode <- "cache"
cache_3rpsX2min$mode <- "cache"
cache_5rpsX2min$mode <- "cache"
cache_7rpsX2min$mode <- "cache"
cache_10rpsX2min$mode <- "cache"

load_1rpsX2min <- bind_rows(normal_1rpsX2min, cache_1rpsX2min)
load_3rpsX2min <- bind_rows(normal_3rpsX2min, cache_3rpsX2min)
load_5rpsX2min <- bind_rows(normal_5rpsX2min, cache_5rpsX2min)
load_7rpsX2min <- bind_rows(normal_7rpsX2min, cache_7rpsX2min)
load_10rpsX2min <- bind_rows(normal_10rpsX2min, cache_10rpsX2min)
```

# Viewing data

```{r}
ggplot(load_5rpsX2min) + 
  geom_bar(aes(x = responseCode), fill = c("dodgerblue")) + 
  facet_grid(.~mode) +
  labs(
    title = "Códigos de respuesta para 5rps/2min", 
    x = "Número de respuesta", 
    y = "Frecuencia absoluta"
  )
```

```{r}
ggplot(load_10rpsX2min) + 
  geom_bar(aes(x = responseCode), fill = c("dodgerblue")) + 
  facet_grid(.~mode) + 
  labs(
    title = "Códigos de respuesta para 10rps/2min", 
    x = "Número de respuesta", 
    y = "Frecuencia absoluta"
  )
```

Filter the data for only use response codes 200.
```{r}
load_5rpsX2min <- subset(load_5rpsX2min, responseCode == "200")
load_10rpsX2min <- subset(load_10rpsX2min, responseCode == "200")
```


```{r}
ggplot(load_5rpsX2min) +
  geom_boxplot(aes(x = mode, y = Latency)) +
  labs(
    title = "Representación de caja por cada fuente [5rps/2min]", 
    x = "Fuente", 
    y = "Latencia [ms]"
  )

ggplot(load_10rpsX2min) +
  geom_boxplot(aes(x = mode, y = Latency)) +
  labs(
    title = "Representación de caja por cada fuente [10rps/2min]", 
    x = "Fuente", 
    y = "Latencia [ms]"
  )
```


```{r}
ggplot(load_5rpsX2min) + 
  geom_point(aes(x = Latency, y = elapsed, color = mode)) + 
  facet_wrap(~mode) + 
  labs(
    title = "Diagrama de puntos de latencia contra tiempo total [5rps/2min]", 
    x = "Latencia [ms]", 
    y = "Tiempo total [ms]"
  ) + 
  scale_color_manual(values = c("indianred1", "lightskyblue"))

ggplot(load_10rpsX2min) + 
  geom_point(aes(x = Latency, y = elapsed, color = mode)) + 
  facet_wrap(~mode) + 
  labs(
    title = "Diagrama de puntos de latencia contra tiempo total [10rps/2min]", 
    x = "Latencia [ms]", 
    y = "Tiempo total [ms]"
  ) + 
  scale_color_manual(values = c("indianred1", "lightskyblue"))
```

```{r}
ggplot(load_5rpsX2min) + 
  geom_density(aes(x = Latency, color = mode, fill = mode), alpha = 0.9) + 
  labs(
    title = "Curvas de densidad por cada fuente [5rps/2min]", 
    x = "Latencia [ms]", 
    y = "Densidad"
  ) + 
  scale_color_manual(values = c("indianred1", "lightskyblue")) + 
  scale_fill_manual(values = c("indianred1", "lightskyblue"))

ggplot(load_10rpsX2min) + 
  geom_density(aes(x = Latency, color = mode, fill = mode), alpha = 0.9) + 
  labs(
    title = "Curvas de densidad por cada fuente [10rps/2min]", 
    x = "Latencia [ms]", 
    y = "Densidad"
  ) + 
  scale_color_manual(values = c("indianred1", "lightskyblue")) + 
  scale_fill_manual(values = c("indianred1", "lightskyblue"))
```

Time series using Epoch:
```{r}
ggplot(load_5rpsX2min) + 
  geom_line(aes(x = timeStamp, y = Latency, color = mode)) + 
  facet_wrap(~mode, nrow = 2, ncol = 1, scales = "free") + 
  labs(
    title = "Serie de tiempo para la latencia [5rps/2min]", 
    x = "Linea de tiempo normalizada", 
    y = "Latencia [ms]"
  ) + 
  scale_color_manual(values = c("indianred1", "lightskyblue"))

ggplot(load_10rpsX2min) + 
  geom_line(aes(x = timeStamp, y = Latency, color = mode)) + 
  facet_wrap(~mode, nrow = 2, ncol = 1, scales = "free") + 
  labs(
    title = "Serie de tiempo para la latencia [10rps/2min]", 
    x = "Linea de tiempo normalizada", 
    y = "Latencia [ms]"
  ) + 
  scale_color_manual(values = c("indianred1", "lightskyblue"))
```



